# Autofill mappings from official USCIS AcroForm field names to our internal
# data paths (resolved by app.services.form_data.resolve_source against the
# context built by build_case_context).
#
# These cover the core biographic/address/contact fields -- name, DOB, country
# of birth, A-Number, mailing address, sex, marital status, SSN, phone/email --
# verified against the field names and page layout of each downloaded PDF (see
# backend/form_templates/). Every other
# field on the form is still part of the electronic form (see field_schema,
# loaded from app/seed_data/field_inventories/*.json, which lists all ~438-97
# fields with their official USCIS label) -- it's just not pre-filled
# automatically, and is left for the attorney/paralegal to complete in the
# form editor before generating the final PDF.

I_130_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt2Line4a_FamilyName[0]", "source": "petitioner.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt2Line4b_GivenName[0]", "source": "petitioner.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt2Line4c_MiddleName[0]", "source": "petitioner.middle_name"},
    {"pdf_field": "form1[0].#subform[0].#area[4].Pt2Line1_AlienNumber[0]", "source": "petitioner.a_number"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line7_CountryofBirth[0]", "source": "petitioner.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line8_DateofBirth[0]", "source": "petitioner.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line10_StreetNumberName[0]", "source": "petitioner.address_line"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line10_CityOrTown[0]", "source": "petitioner.city"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line10_State[0]", "source": "petitioner.state"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line10_ZipCode[0]", "source": "petitioner.zip_code"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line10_Country[0]", "source": "petitioner.country"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line4a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line4b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line4c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[4].#area[6].Pt4Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line8_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line9_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line11_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line11_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line11_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line11_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line11_Country[0]", "source": "beneficiary.country"},
    # Petitioner -- sex, marital status (Part 2), SSN, and contact info (Part 6)
    {"pdf_field": "form1[0].#subform[1].Pt2Line9_Male[0]", "source": "petitioner.sex", "match_value": "male", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line9_Female[0]", "source": "petitioner.sex", "match_value": "female", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Single[0]", "source": "petitioner.marital_status", "match_value": "single", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Married[0]", "source": "petitioner.marital_status", "match_value": "married", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Divorced[0]", "source": "petitioner.marital_status", "match_value": "divorced", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Widowed[0]", "source": "petitioner.marital_status", "match_value": "widowed", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Separated[0]", "source": "petitioner.marital_status", "match_value": "separated", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line17_Annulled[0]", "source": "petitioner.marital_status", "match_value": "annulled", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[0].Pt2Line11_SSN[0]", "source": "petitioner.ssn"},
    {"pdf_field": "form1[0].#subform[8].Pt6Line3_DaytimePhoneNumber[0]", "source": "petitioner.phone"},
    {"pdf_field": "form1[0].#subform[8].Pt6Line4_MobileNumber[0]", "source": "petitioner.mobile_phone"},
    {"pdf_field": "form1[0].#subform[8].Pt6Line5_Email[0]", "source": "petitioner.email"},
    # Beneficiary -- sex, marital status (Part 4), SSN, contact info
    {"pdf_field": "form1[0].#subform[4].Pt4Line9_Male[0]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line9_Female[0]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[3]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/SNM"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[4]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[5]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/D"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[0]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/W"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[2]", "source": "beneficiary.marital_status", "match_value": "separated", "set_value": "/S"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line18_MaritalStatus[1]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/A"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line3_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[4].Pt4Line14_DaytimePhoneNumber[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line15_MobilePhoneNumber[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[5].Pt4Line16_EmailAddress[0]", "source": "beneficiary.email"},
]

I_765_AUTOFILL = [
    {"pdf_field": "form1[0].Page1[0].Line1a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].Page1[0].Line1b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].Page1[0].Line1c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].Page2[0].Line7_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].Page3[0].Line19_DOB[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].Page3[0].Line18c_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].Page2[0].Line4b_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].Page2[0].Pt2Line5_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].Page2[0].Pt2Line5_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].Page2[0].Pt2Line5_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].Page2[0].Line12b_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].Page4[0].Pt3Line3_DaytimePhoneNumber1[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].Page4[0].Pt3Line4_MobileNumber1[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].Page4[0].Pt3Line5_Email[0]", "source": "beneficiary.email"},
]

G_28_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line2a_FamilyName[0]", "source": "attorney.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line2b_GivenName[0]", "source": "attorney.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt2Line1b_BarNumber[0]", "source": "attorney.bar_number"},
    {"pdf_field": "form1[0].#subform[0].Pt2Line1d_NameofFirmOrOrganization[0]", "source": "attorney.firm_name"},
    {"pdf_field": "form1[0].#subform[0].Line3a_StreetNumber[0]", "source": "attorney.address_line"},
    {"pdf_field": "form1[0].#subform[0].Line3c_CityOrTown[0]", "source": "attorney.city"},
    {"pdf_field": "form1[0].#subform[0].Line3e_ZipCode[0]", "source": "attorney.zip_code"},
    {"pdf_field": "form1[0].#subform[0].Line4_DaytimeTelephoneNumber[0]", "source": "attorney.phone"},
    # USCIS's own G-28 PDF has these two fields' internal names and tooltip
    # text crossed: the field literally named "Line6_EMail" has a tooltip of
    # "5. Enter Mobile Telephone Number", and "Line7_MobileTelephoneNumber"'s
    # tooltip says "6. Enter Email Address" (see field_inventories/g-28.json,
    # which is extracted straight from the real PDF's own metadata -- this
    # isn't our extraction bug). Mapping by the tooltip's real meaning, not
    # the misleading internal name, so the value both displays under the
    # correct label *and* lands on the correct physical line when filled.
    {"pdf_field": "form1[0].#subform[0].Line6_EMail[0]", "source": "attorney.mobile_phone"},
    {"pdf_field": "form1[0].#subform[0].Line7_MobileTelephoneNumber[0]", "source": "attorney.email"},
    {"pdf_field": "form1[0].#subform[1].Pt3Line5a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[1].Pt3Line5b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[1].Pt3Line5c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[1].Pt3Line9_ANumber[0]", "source": "beneficiary.a_number"},
]

# Forms added in bulk from an official-PDF download batch (see field
# inventories in app/seed_data/field_inventories/*.json, extracted with
# scripts/extract_form_fields.py). Each of these autofill maps only covers
# the applicant's own core biographic/contact fields on Part 1 (or
# equivalent), verified by field name/page against the tooltip label in the
# inventory JSON -- same curated-subset approach as I-130/I-765/G-28 above,
# not full coverage. None of these forms have conditional_rules.py entries
# yet (see backend/README section "Formulario dinámico") -- that requires
# reading each form's actual instructions for "If you answered..." gating
# per field, which wasn't done for this batch; every field is shown
# unconditionally until that's added form-by-form.
I_130A_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line3a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line3b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line3c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    # No DOB/country-of-birth/SSN fields on this form -- I-130A only asks for
    # address/employment history and parent info, the biographic basics are
    # already on the main I-130.
    {"pdf_field": "form1[0].#subform[0].Pt1Line4a_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line4c_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line4d_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line4e_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[2].Pt4Line3_DaytimePhoneNumber1[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[2].Pt4Line4_MobileNumber1[0]", "source": "beneficiary.mobile_phone"},
]
I_131_AUTOFILL = [
    {"pdf_field": "form1[0].P4[0].Part2_Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].P4[0].Part2_Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].P4[0].Part2_Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].P5[0].#area[0].Part2_Line5_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].P5[0].Part2_Line6_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].P5[0].Part2_Line9_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].P5[0].#area[1].Part2_Line10_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].P5[0].Part2_Line3_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].P5[0].Part2_Line3_CityTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].P5[0].Part2_Line3_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].P5[0].Part2_Line3_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].P5[0].Part2_Line3_Country[0]", "source": "beneficiary.country"},
    {"pdf_field": "form1[0].P6[0].P2_Line21_DaytimeTelephoneNumber[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[10].Part10_Line2_MobilePhone[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].P6[0].P2_Line22_Email[0]", "source": "beneficiary.email"},
]
I_485_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line3_DOB[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line4_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line7_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[3].Pt1Line19_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[2].Pt1Line18_CurrentStreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[2].Pt1Line18_CurrentCityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[2].Pt1Line18_CurrentState[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[2].Pt1Line18_CurrentZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line6_CB_Sex[1]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line6_CB_Sex[0]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/F"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[1]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/1"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[3]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/2"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[0]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/3"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[2]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/4"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[5]", "source": "beneficiary.marital_status", "match_value": "separated", "set_value": "/7"},
    {"pdf_field": "form1[0].#subform[9].Pt6Line1_MaritalStatus[4]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/5"},
    {"pdf_field": "form1[0].#subform[22].Pt3Line3_DaytimePhoneNumber1[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[22].Pt3Line4_MobileNumber1[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[22].Pt3Line5_Email[0]", "source": "beneficiary.email"},
]
I_589_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].PtAILine4_LastName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].PtAILine5_FirstName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].PtAILine6_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].PtAILine1_ANumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[0].DateTimeField1[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[0].TextField1[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[0].PtAILine8_StreetNumandName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[0].TextField1[2]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[0].PtAILine8_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[0].PtAILine8_Zipcode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[0].PartALine9Sex[0]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[0].PartALine9Sex[1]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/F"},
    {"pdf_field": "form1[0].#subform[0].Marital[0]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/S"},
    {"pdf_field": "form1[0].#subform[0].Marital[1]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[0].Marital[2]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/D"},
    {"pdf_field": "form1[0].#subform[0].Marital[3]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/W"},
]
I_751_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line1a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].P1_Line7_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[0].P1_Line4_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[0].P1_Line5_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[0].P1_Line8_SSN[0]", "source": "beneficiary.ssn"},
    # Item 15 (Mailing Address) -- not item 17 (Physical Address, only shown
    # if different from mailing, see I_751_CONDITIONS in conditional_rules.py).
    {"pdf_field": "form1[0].#subform[1].Line17b_Street_Number_Name[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[1].Line17d_City_Town[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line15e_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line15f_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[5].P5_Line3_DaytimePhoneNumber[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[5].P5_Line4_MobilePhoneNumber[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[5].P5_Line5_EmailAddress[0]", "source": "beneficiary.email"},
]
I_864_AUTOFILL = [
    # Part 2 -- the sponsor's own info.
    {"pdf_field": "form1[0].#subform[0].P4_Line1a_FamilyName[0]", "source": "sponsor.last_name"},
    {"pdf_field": "form1[0].#subform[0].P4_Line1b_GivenName[0]", "source": "sponsor.first_name"},
    {"pdf_field": "form1[0].#subform[0].P4_Line1c_MiddleName[0]", "source": "sponsor.middle_name"},
    {"pdf_field": "form1[0].#subform[1].#area[1].P4_Line12_AlienNumber[0]", "source": "sponsor.a_number"},
    {"pdf_field": "form1[0].#subform[1].P4_Line6_DateOfBirth[0]", "source": "sponsor.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P4_Line7_CityofBirth[0]", "source": "sponsor.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P4_Line10_SocialSecurityNumber[0]", "source": "sponsor.ssn"},
    {"pdf_field": "form1[0].#subform[1].P4_Line2b_StreetNumberName[0]", "source": "sponsor.address_line"},
    {"pdf_field": "form1[0].#subform[1].P4_Line2e_CityOrTown[0]", "source": "sponsor.city"},
    {"pdf_field": "form1[0].#subform[1].P4_Line2f_State[0]", "source": "sponsor.state"},
    {"pdf_field": "form1[0].#subform[1].P4_Line2g_ZipCode[0]", "source": "sponsor.zip_code"},
    {"pdf_field": "form1[0].#subform[9].P8_Line3_DaytimeTelephoneNumber[0]", "source": "sponsor.phone"},
    {"pdf_field": "form1[0].#subform[9].P8_Line4_MobileTelephoneNumber[0]", "source": "sponsor.mobile_phone"},
    {"pdf_field": "form1[0].#subform[9].P7Line7_EmailAddress[0]", "source": "sponsor.email"},
    # Part 3 -- the principal immigrant being sponsored.
    {"pdf_field": "form1[0].#subform[2].P2_Line1a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[2].P2_Line1b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[2].P2_Line1c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[2].#area[2].P2_Line5_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[2].P2_Line4_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[2].P2_Line2_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[2].P2_Line2_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[2].P2_Line2_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[2].P2_Line2_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[2].P2_Line7_DaytimePhoneNumber[0]", "source": "beneficiary.phone"},
]
I_90_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].P1_Line3a_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].P1_Line3b_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].P1_Line3c_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].#area[1].P1_Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].P1_Line9_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P1_Line11_CountryofBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P1_Line16_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[0].P1_Line6b_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[0].P1_Line6d_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[0].P1_Line6e_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[0].P1_Line6f_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].P1_Line8_male[0]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[1].P1_Line8_female[0]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/Y"},
    {"pdf_field": "form1[0].#subform[3].P5_Line3_DaytimePhoneNumber[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[3].P5_Line4_MobilePhoneNumber[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[3].P5_Line5_EmailAddress[0]", "source": "beneficiary.email"},
]
N_336_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[0].Line6_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line5_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line5_CityOrTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line5_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line5_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[3].Pt5Line3_DaytimeTelephoneNumber3[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[3].Pt5Line4_MobileTelephoneNumber3[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[3].Pt5Line5_Email[0]", "source": "beneficiary.email"},
]
N_400_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].P2_Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].P2_Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].P2_Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].#area[0].Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].P2_Line8_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P2_Line10_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Line12b_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[2].P4_Line1_StreetName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[2].P4_Line1_City[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[2].P4_Line1_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[2].P4_Line1_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].P2_Line7_Gender[0]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[1].P2_Line7_Gender[1]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/F"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[1]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/S"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[3]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[0]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/D"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[2]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/W"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[5]", "source": "beneficiary.marital_status", "match_value": "separated", "set_value": "/E"},
    {"pdf_field": "form1[0].#subform[3].P10_Line1_MaritalStatus[4]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/A"},
    {"pdf_field": "form1[0].#subform[10].P12_Line3_Telephone[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[10].P12_Line3_Mobile[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[10].P12_Line5_Email[0]", "source": "beneficiary.email"},
]
N_470_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line8_AlienNumber[1]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].Line6_DateOfBirth[9]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line6_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].Pt1Line10_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[1].Pt11Line10_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[1].Pt11Line3_CityOrTown[1]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[1].Pt11Line3_State[1]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[1].Pt11Line3_ZipCode[1]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[4].Pt3Line4_DaytimeTelephoneNumber3[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[4].Pt3Line5_MobileTelephoneNumber3[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[4].Pt3Line6_Email[1]", "source": "beneficiary.email"},
]
N_565_AUTOFILL = [
    # Part 2 "Current Information About You" -- the name line sits in
    # subform[0] in the real PDF even though the rest of Part 2 (address,
    # marital status) is subform[1]; verified against field_inventories/n-565.json.
    {"pdf_field": "form1[0].#subform[0].P2_Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].ANum[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line2_DateofBirthonCert[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[0]._CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P2Line3_StreetNumberName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[1].Pt2Line3_CityTown[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[1].P2Line3_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[1].P2Line3_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].Part2_Item5[0]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/Married"},
    {"pdf_field": "form1[0].#subform[1].Part2_Item5[1]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/Single"},
    {"pdf_field": "form1[0].#subform[1].Part2_Item5[2]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/Widowed"},
    {"pdf_field": "form1[0].#subform[1].Part2_Item5[3]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/Divorced"},
    {"pdf_field": "form1[0].#subform[1].Part2_Item5[4]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/MarriageAnn"},
    {"pdf_field": "form1[0].#subform[4].Pt9Line3_DaytimeTelephoneNumber3[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[4].Pt9Line4_MobileTelephoneNumber3[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[4].Pt9Line5_Email[0]", "source": "beneficiary.email"},
]
N_600_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[0].Pt1Line1_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].#subform[0].#area[0].Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].#area[3].P2_Line8_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].#area[4].P2_Line10_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].#subform[1].P1_Line4_SSN[0]", "source": "beneficiary.ssn"},
    {"pdf_field": "form1[0].#subform[1].#subform[4].P2_Line10_StreetName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].#subform[1].#subform[4].Pt2_Line10_City[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].#subform[1].#subform[4].Pt2Line10_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].#subform[1].#subform[4].Pt2Line10_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[1]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/S"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[3]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[0]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/D"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[2]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/W"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[4]", "source": "beneficiary.marital_status", "match_value": "separated", "set_value": "/E"},
    {"pdf_field": "form1[0].#subform[1].P2_Line12_MaritalStatus[6]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/A"},
    {"pdf_field": "form1[0].#subform[12].P8_Line3[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].#subform[12].P8_Line4[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].#subform[12].P8_Line5[0]", "source": "beneficiary.email"},
]
N_600K_AUTOFILL = [
    {"pdf_field": "form1[0].#subform[1].Part3_Item2_FamilyName[0]", "source": "beneficiary.last_name"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item2_GivenName[0]", "source": "beneficiary.first_name"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item2_MiddleName[0]", "source": "beneficiary.middle_name"},
    {"pdf_field": "form1[0].Page1[0].Child-A-Number[0].Line1_AlienNumber[0]", "source": "beneficiary.a_number"},
    {"pdf_field": "form1[0].#subform[1].#area[2].Part3_Item5_DateOfBirth[0]", "source": "beneficiary.date_of_birth"},
    {"pdf_field": "form1[0].#subform[1].#area[0].Part3_Item6_CountryOfBirth[0]", "source": "beneficiary.country_of_birth"},
    {"pdf_field": "form1[0].Page2[0].PhysicalAddress[0].Part3_Item112_ChildStreetName[0]", "source": "beneficiary.address_line"},
    {"pdf_field": "form1[0].Page2[0].PhysicalAddress[0].Part3_Item12_City[0]", "source": "beneficiary.city"},
    {"pdf_field": "form1[0].Page2[0].PhysicalAddress[0].Part3_Item12_State[0]", "source": "beneficiary.state"},
    {"pdf_field": "form1[0].Page2[0].PhysicalAddress[0].Part3_Item12_ZipCode[0]", "source": "beneficiary.zip_code"},
    {"pdf_field": "form1[0].#subform[1].#area[3].Part3_Item8_Sex[0]", "source": "beneficiary.sex", "match_value": "male", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[1].#area[3].Part3_Item8_Sex[1]", "source": "beneficiary.sex", "match_value": "female", "set_value": "/F"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[0]", "source": "beneficiary.marital_status", "match_value": "single", "set_value": "/S"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[1]", "source": "beneficiary.marital_status", "match_value": "married", "set_value": "/M"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[2]", "source": "beneficiary.marital_status", "match_value": "divorced", "set_value": "/D"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[3]", "source": "beneficiary.marital_status", "match_value": "widowed", "set_value": "/W"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[4]", "source": "beneficiary.marital_status", "match_value": "separated", "set_value": "/E"},
    {"pdf_field": "form1[0].#subform[1].Part3_Item10_MaritalStatus[5]", "source": "beneficiary.marital_status", "match_value": "annulled", "set_value": "/A"},
    {"pdf_field": "form1[0].Page6[0].Part10_Item1_DayPhone[0]", "source": "beneficiary.phone"},
    {"pdf_field": "form1[0].Page6[0].Part10_Item2_MobilePhone[0]", "source": "beneficiary.mobile_phone"},
    {"pdf_field": "form1[0].Page6[0].Part100_Item3_Email[0]", "source": "beneficiary.email"},
]

FORM_TEMPLATES = [
    {
        "code": "I-130",
        "name": "Petition for Alien Relative",
        "edition_date": "04/01/24",
        "pdf_template_path": "i-130.pdf",
        "inventory_file": "i-130.json",
        "autofill_map": I_130_AUTOFILL,
    },
    {
        "code": "I-765",
        "name": "Application for Employment Authorization",
        "edition_date": "08/21/25",
        "pdf_template_path": "i-765.pdf",
        "inventory_file": "i-765.json",
        "autofill_map": I_765_AUTOFILL,
    },
    {
        "code": "G-28",
        "name": "Notice of Entry of Appearance as Attorney or Accredited Representative",
        "edition_date": "09/17/18",
        "pdf_template_path": "g-28.pdf",
        "inventory_file": "g-28.json",
        "autofill_map": G_28_AUTOFILL,
    },
    {
        "code": "I-130A",
        "name": "Supplemental Information for Spouse Beneficiary",
        "edition_date": "04/01/24",
        "pdf_template_path": "i-130a.pdf",
        "inventory_file": "i-130a.json",
        "autofill_map": I_130A_AUTOFILL,
    },
    {
        "code": "I-131",
        "name": "Application for Travel Document",
        "edition_date": "01/20/25",
        "pdf_template_path": "i-131.pdf",
        "inventory_file": "i-131.json",
        "autofill_map": I_131_AUTOFILL,
    },
    {
        "code": "I-485",
        "name": "Application to Register Permanent Residence or Adjust Status",
        "edition_date": "01/20/25",
        "pdf_template_path": "i-485.pdf",
        "inventory_file": "i-485.json",
        "autofill_map": I_485_AUTOFILL,
    },
    {
        "code": "I-589",
        "name": "Application for Asylum and for Withholding of Removal",
        "edition_date": "01/20/25",
        "pdf_template_path": "i-589.pdf",
        "inventory_file": "i-589.json",
        "autofill_map": I_589_AUTOFILL,
    },
    {
        "code": "I-751",
        "name": "Petition to Remove Conditions on Residence",
        "edition_date": "04/01/24",
        "pdf_template_path": "i-751.pdf",
        "inventory_file": "i-751.json",
        "autofill_map": I_751_AUTOFILL,
    },
    {
        "code": "I-864",
        "name": "Affidavit of Support Under Section 213A of the INA",
        "edition_date": "10/17/24",
        "pdf_template_path": "i-864.pdf",
        "inventory_file": "i-864.json",
        "autofill_map": I_864_AUTOFILL,
    },
    {
        "code": "I-90",
        "name": "Application to Replace Permanent Resident Card",
        "edition_date": "01/20/25",
        "pdf_template_path": "i-90.pdf",
        "inventory_file": "i-90.json",
        "autofill_map": I_90_AUTOFILL,
    },
    {
        "code": "N-336",
        "name": "Request for a Hearing on a Decision in Naturalization Proceedings",
        "edition_date": "04/01/24",
        "pdf_template_path": "n-336.pdf",
        "inventory_file": "n-336.json",
        "autofill_map": N_336_AUTOFILL,
    },
    {
        "code": "N-400",
        "name": "Application for Naturalization",
        "edition_date": "01/20/25",
        "pdf_template_path": "n-400.pdf",
        "inventory_file": "n-400.json",
        "autofill_map": N_400_AUTOFILL,
    },
    {
        "code": "N-470",
        "name": "Application to Preserve Residence for Naturalization Purposes",
        "edition_date": "04/01/24",
        "pdf_template_path": "n-470.pdf",
        "inventory_file": "n-470.json",
        "autofill_map": N_470_AUTOFILL,
    },
    {
        "code": "N-565",
        "name": "Application for Replacement Naturalization/Citizenship Document",
        "edition_date": "02/27/25",
        "pdf_template_path": "n-565.pdf",
        "inventory_file": "n-565.json",
        "autofill_map": N_565_AUTOFILL,
    },
    {
        "code": "N-600",
        "name": "Application for Certificate of Citizenship",
        "edition_date": "01/20/25",
        "pdf_template_path": "n-600.pdf",
        "inventory_file": "n-600.json",
        "autofill_map": N_600_AUTOFILL,
    },
    {
        "code": "N-600K",
        "name": "Application for Citizenship and Issuance of Certificate Under Section 322",
        "edition_date": "01/20/25",
        "pdf_template_path": "n-600k.pdf",
        "inventory_file": "n-600k.json",
        "autofill_map": N_600K_AUTOFILL,
    },
]
