"""add rfes and rfe_evidence_items tables

Revision ID: 1cd1e24b8bea
Revises: e9113769dd84
Create Date: 2026-07-18 13:33:19.846326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd1e24b8bea'
down_revision: Union[str, None] = 'e9113769dd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious notifications.type type-change autogenerate detected here --
    # same VARCHAR/Enum artifact as in prior migrations, omitted; see those
    # for why.)
    op.create_table('rfes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESPONDED', 'CLOSED', name='rfestatus'), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfe_evidence_items',
    sa.Column('rfe_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GATHERED', 'SUBMITTED', name='rfeevidencestatus'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rfe_id'], ['rfes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfe_evidence_items')
    op.drop_table('rfes')
    # ### end Alembic commands ###
