"""add uscis case status tracking to generated forms

Revision ID: 277d73d31f9e
Revises: 70fa9e733dce
Create Date: 2026-07-19 21:26:44.109967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277d73d31f9e'
down_revision: Union[str, None] = '70fa9e733dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious notifications.type type-change autogenerate detected here --
    # same VARCHAR/Enum artifact as in prior migrations, omitted; see those
    # for why.)
    op.add_column('generated_forms', sa.Column('uscis_receipt_number', sa.String(length=20), nullable=True))
    op.add_column('generated_forms', sa.Column('uscis_status_raw', sa.JSON(), nullable=True))
    op.add_column('generated_forms', sa.Column('uscis_status_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_generated_forms_uscis_receipt_number'), 'generated_forms', ['uscis_receipt_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_forms_uscis_receipt_number'), table_name='generated_forms')
    op.drop_column('generated_forms', 'uscis_status_checked_at')
    op.drop_column('generated_forms', 'uscis_status_raw')
    op.drop_column('generated_forms', 'uscis_receipt_number')
    # ### end Alembic commands ###
