"""Add denied_tokens and ai_call_audits tables

Revision ID: 36635b30dde7
Revises: 559bb8e7d03d
Create Date: 2026-07-20 16:50:14.226343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36635b30dde7'
down_revision: Union[str, None] = '559bb8e7d03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_audits',
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_audits_model'), 'ai_call_audits', ['model'], unique=False)
    op.create_index(op.f('ix_ai_call_audits_prompt_hash'), 'ai_call_audits', ['prompt_hash'], unique=False)
    op.create_table('denied_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denied_tokens_expires_at'), 'denied_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_denied_tokens_jti'), 'denied_tokens', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_denied_tokens_jti'), table_name='denied_tokens')
    op.drop_index(op.f('ix_denied_tokens_expires_at'), table_name='denied_tokens')
    op.drop_table('denied_tokens')
    op.drop_index(op.f('ix_ai_call_audits_prompt_hash'), table_name='ai_call_audits')
    op.drop_index(op.f('ix_ai_call_audits_model'), table_name='ai_call_audits')
    op.drop_table('ai_call_audits')
    # ### end Alembic commands ###
