"""add sex, marital_status, ssn, mobile_phone to clients and users

Revision ID: 54c6e64fb495
Revises: ce511a038d6f
Create Date: 2026-07-17 11:41:57.909678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c6e64fb495'
down_revision: Union[str, None] = 'ce511a038d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('mobile_phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('ssn', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('mobile_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_phone')
    op.drop_column('clients', 'marital_status')
    op.drop_column('clients', 'sex')
    op.drop_column('clients', 'ssn')
    op.drop_column('clients', 'mobile_phone')
    # ### end Alembic commands ###
