"""add client link token to generated forms, nullable password

Revision ID: 5cc3197894db
Revises: 54c6e64fb495
Create Date: 2026-07-17 12:18:10.119011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc3197894db'
down_revision: Union[str, None] = '54c6e64fb495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_forms', sa.Column('access_token', sa.String(length=64), nullable=False))
    op.add_column('generated_forms', sa.Column('client_link_enabled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_generated_forms_access_token'), 'generated_forms', ['access_token'], unique=True)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
    op.drop_index(op.f('ix_generated_forms_access_token'), table_name='generated_forms')
    op.drop_column('generated_forms', 'client_link_enabled')
    op.drop_column('generated_forms', 'access_token')
    # ### end Alembic commands ###
