"""add attorney fields to users

Revision ID: 5d0bb66dc539
Revises: b739f9bf15eb
Create Date: 2026-07-17 10:15:42.058222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0bb66dc539'
down_revision: Union[str, None] = 'b739f9bf15eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bar_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('firm_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('address_line', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address_line')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'firm_name')
    op.drop_column('users', 'bar_number')
    # ### end Alembic commands ###
