"""add missing indexes on foreign key columns

Revision ID: 70fa9e733dce
Revises: 1cd1e24b8bea
Create Date: 2026-07-19 15:54:12.563698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fa9e733dce'
down_revision: Union[str, None] = '1cd1e24b8bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious notifications.type type-change autogenerate detected here --
    # same VARCHAR/Enum artifact as in prior migrations, omitted; see those
    # for why.)
    op.create_index(op.f('ix_appointments_case_id'), 'appointments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_checklist_items_assigned_to_id'), 'case_checklist_items', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_case_checklist_items_case_id'), 'case_checklist_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_case_id'), 'case_participants', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_participants_client_id'), 'case_participants', ['client_id'], unique=False)
    op.create_index(op.f('ix_cases_assigned_attorney_id'), 'cases', ['assigned_attorney_id'], unique=False)
    op.create_index(op.f('ix_cases_service_id'), 'cases', ['service_id'], unique=False)
    op.create_index(op.f('ix_cases_workflow_stage_id'), 'cases', ['workflow_stage_id'], unique=False)
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_generated_forms_case_id'), 'generated_forms', ['case_id'], unique=False)
    op.create_index(op.f('ix_generated_forms_form_template_id'), 'generated_forms', ['form_template_id'], unique=False)
    op.create_index(op.f('ix_invoices_case_id'), 'invoices', ['case_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_notification_id'), 'notification_reads', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_rfe_evidence_items_rfe_id'), 'rfe_evidence_items', ['rfe_id'], unique=False)
    op.create_index(op.f('ix_rfes_case_id'), 'rfes', ['case_id'], unique=False)
    op.create_index(op.f('ix_service_checklist_items_service_id'), 'service_checklist_items', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_form_templates_form_template_id'), 'service_form_templates', ['form_template_id'], unique=False)
    op.create_index(op.f('ix_service_form_templates_service_id'), 'service_form_templates', ['service_id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_service_id'), 'workflow_stages', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_stages_service_id'), table_name='workflow_stages')
    op.drop_index(op.f('ix_service_form_templates_service_id'), table_name='service_form_templates')
    op.drop_index(op.f('ix_service_form_templates_form_template_id'), table_name='service_form_templates')
    op.drop_index(op.f('ix_service_checklist_items_service_id'), table_name='service_checklist_items')
    op.drop_index(op.f('ix_rfes_case_id'), table_name='rfes')
    op.drop_index(op.f('ix_rfe_evidence_items_rfe_id'), table_name='rfe_evidence_items')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_index(op.f('ix_notification_reads_notification_id'), table_name='notification_reads')
    op.drop_index(op.f('ix_invoices_case_id'), table_name='invoices')
    op.drop_index(op.f('ix_generated_forms_form_template_id'), table_name='generated_forms')
    op.drop_index(op.f('ix_generated_forms_case_id'), table_name='generated_forms')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_index(op.f('ix_cases_workflow_stage_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_service_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_attorney_id'), table_name='cases')
    op.drop_index(op.f('ix_case_participants_client_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_participants_case_id'), table_name='case_participants')
    op.drop_index(op.f('ix_case_checklist_items_case_id'), table_name='case_checklist_items')
    op.drop_index(op.f('ix_case_checklist_items_assigned_to_id'), table_name='case_checklist_items')
    op.drop_index(op.f('ix_appointments_case_id'), table_name='appointments')
    # ### end Alembic commands ###
