"""add_e_signature

Revision ID: 754c137df36a
Revises: 36635b30dde7
Create Date: 2026-07-20 18:37:01.695540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_e_signature

Revision ID: 754c137df36a
Revises: 36635b30dde7
Create Date: 2026-07-20 18:37:01.695540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754c137df36a'
down_revision: Union[str, None] = '36635b30dde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_signatures',
    sa.Column('form_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('signer_type', sa.Enum('CLIENT', 'ATTORNEY', 'PREPARER', name='signertype'), nullable=False),
    sa.Column('signer_name', sa.String(length=255), nullable=False),
    sa.Column('signer_email', sa.String(length=255), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_method', sa.Enum('DRAWN', 'TYPED', 'ACCEPTED', name='signaturemethod'), nullable=False),
    sa.Column('signature_value', sa.String(length=64), nullable=False),
    sa.Column('signature_image_path', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['generated_forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_e_signatures_client_id'), 'e_signatures', ['client_id'], unique=False)
    op.create_index(op.f('ix_e_signatures_document_id'), 'e_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_e_signatures_form_id'), 'e_signatures', ['form_id'], unique=False)
    op.create_index(op.f('ix_e_signatures_signer_type'), 'e_signatures', ['signer_type'], unique=False)
    op.create_index(op.f('ix_e_signatures_user_id'), 'e_signatures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_e_signatures_user_id'), table_name='e_signatures')
    op.drop_index(op.f('ix_e_signatures_signer_type'), table_name='e_signatures')
    op.drop_index(op.f('ix_e_signatures_form_id'), table_name='e_signatures')
    op.drop_index(op.f('ix_e_signatures_document_id'), table_name='e_signatures')
    op.drop_index(op.f('ix_e_signatures_client_id'), table_name='e_signatures')
    op.drop_table('e_signatures')
    # ### end Alembic commands ###
