"""add checklist assignee due date and priority

Revision ID: 7f3b563f13bb
Revises: 972b7b32fe71
Create Date: 2026-07-17 15:35:54.703403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3b563f13bb'
down_revision: Union[str, None] = '972b7b32fe71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('type', sa.Enum('CASE_ASSIGNED', 'STAGE_ADVANCED', 'DOCUMENT_UPLOADED', 'AI_REVIEW_FLAGGED', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_checklist_items') as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'priority',
                sa.Enum('LOW', 'MEDIUM', 'HIGH', name='checklistpriority'),
                nullable=False,
                server_default='MEDIUM',
            )
        )
        batch_op.create_foreign_key('fk_case_checklist_items_assigned_to_id', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_checklist_items') as batch_op:
        batch_op.drop_constraint('fk_case_checklist_items_assigned_to_id', type_='foreignkey')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')
        batch_op.drop_column('assigned_to_id')
    op.drop_table('notifications')
    # ### end Alembic commands ###
