"""add ai review to generated forms

Revision ID: 972b7b32fe71
Revises: d5a87cc451a2
Create Date: 2026-07-17 14:51:25.201793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972b7b32fe71'
down_revision: Union[str, None] = 'd5a87cc451a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_forms', sa.Column('ai_review', sa.JSON(), nullable=True))
    op.add_column('generated_forms', sa.Column('ai_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_forms', 'ai_reviewed_at')
    op.drop_column('generated_forms', 'ai_review')
    # ### end Alembic commands ###
