"""add autofill_map to form_templates

Revision ID: ce511a038d6f
Revises: 5d0bb66dc539
Create Date: 2026-07-17 10:25:29.913748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce511a038d6f'
down_revision: Union[str, None] = '5d0bb66dc539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_templates', sa.Column('autofill_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_templates', 'autofill_map')
    # ### end Alembic commands ###
