"""add service catalog and workflow

Revision ID: d5a87cc451a2
Revises: 5cc3197894db
Create Date: 2026-07-17 12:48:51.790473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a87cc451a2'
down_revision: Union[str, None] = '5cc3197894db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_checklist_items',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_form_templates',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('form_template_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_stages',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_checklist_items',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases') as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('workflow_stage_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_cases_service_id', 'services', ['service_id'], ['id'])
        batch_op.create_foreign_key('fk_cases_workflow_stage_id', 'workflow_stages', ['workflow_stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases') as batch_op:
        batch_op.drop_constraint('fk_cases_workflow_stage_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cases_service_id', type_='foreignkey')
        batch_op.drop_column('workflow_stage_id')
        batch_op.drop_column('service_id')
    op.drop_table('case_checklist_items')
    op.drop_table('workflow_stages')
    op.drop_table('service_form_templates')
    op.drop_table('service_checklist_items')
    op.drop_table('services')
    # ### end Alembic commands ###
