"""add login lockout fields to users

Revision ID: e9113769dd84
Revises: 6afb3eaaeea8
Create Date: 2026-07-18 09:55:35.155935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9113769dd84'
down_revision: Union[str, None] = '6afb3eaaeea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious notifications.type type-change autogenerate detected here --
    # same VARCHAR/Enum artifact as in prior migrations, omitted; see those
    # for why.)
    # server_default so this doesn't break on existing rows (e.g. the seeded
    # admin) -- Python-side `default=0` on the model only applies to new
    # ORM-issued inserts, not to backfilling a NOT NULL column being added.
    op.add_column(
        'users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
