"""add client wizard step to generated forms

Revision ID: f2bd413672a4
Revises: 277d73d31f9e
Create Date: 2026-07-19 23:53:50.118499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bd413672a4'
down_revision: Union[str, None] = '277d73d31f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Spurious notifications.type type-change autogenerate detected here --
    # same VARCHAR/Enum artifact as in prior migrations, omitted; see those
    # for why.)
    # server_default so SQLite can backfill existing rows for the new
    # NOT NULL column; matches the ORM-level default=0 in models/form.py.
    op.add_column('generated_forms', sa.Column('client_wizard_step', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_forms', 'client_wizard_step')
    # ### end Alembic commands ###
